version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      CLUSTER_ID: "fNmrFBcWRWSfj62QmSrfkw"
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLE: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0.kafka-headless.kafka.svc.cluster.local:9093
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-0.kafka-headless.kafka.svc.cluster.local:9092,CONTROLLER://$(POD_NAME).kafka-headless.kafka.svc.cluster.local:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIR: /tmp/kafka-logs
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data:

